version: '3.5'
services:
    postgres:
        restart: always
        image: postgres:10
        env_file:
            - db-vars.env
        volumes:
          - ./postgres-db-init.sh:/docker-entrypoint-initdb.d/postgres-db-init.sh
          - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
#        networks:
#            - auth_network

    auth-app:
        restart: always
        # network_mode: host
        build: .
        ports:    
            - 8000:8000
        depends_on: 
            - postgres

    products-app:
        restart: always
        build: ./../flask-products
        tty: true   # output za testovite, probaj bez 
        ports:    
            - 5000:5000
        depends_on: 
            - postgres

#networks:
#  auth_network:
#    name: project_network

volumes:
  db-data:
    driver: local