apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-auth-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-auth
  template:
    metadata:
      labels:
        app: fastapi-auth
    spec:
      hostNetwork: true
      containers:
        - name: auth-image
          image: evgenija1/auth-image:a3c749771bdbc0a53f0b94de27e1d3ac8f207baf
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_PORT
            - name: POSTGRES_DATABASE_FASTAPI
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_DATABASE_FASTAPI
                  
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_VERIFY_SERVICE
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_VERIFY_SERVICE
            - name: TWILIO_MESSAGING_LOGIN_SERVICE_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_MESSAGING_LOGIN_SERVICE_SID

            - name: expire
              valueFrom:
                secretKeyRef:
                  name: encoding-secret
                  key: expire
            - name: secret
              valueFrom:
                secretKeyRef:
                  name: encoding-secret
                  key: secret
            - name: algorithm
              valueFrom:
                secretKeyRef:
                  name: encoding-secret
                  key: algorithm
            
          resources:
            requests:
              memory: 100Mi
              cpu: 100m