apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXMK 
  POSTGRES_PASSWORD: YWRtaW4K
  POSTGRES_HOST: cG9zdGdyZXMuZGVmYXVsdAo=
  POSTGRES_PORT: NTQzMgo=
  POSTGRES_DATABASE_FLASK: Zmxhc2tfcHJvZHVjdHMK
  POSTGRES_DATABASE_FASTAPI: YXV0aF91c2Vycwo=


  