---
apiVersion: argoproj.io/v1alpha1
kind: EventSource     #tuka definirame event source, vo slucajov github webhook (listener)
metadata:
  name: fastapi-github-event-source 
  namespace: argo-events
spec:
  service:
    ports:
    - port: 12001
      targetPort: 12001
  github:
    auth-webhook:      #imeto na github webhook (listenerot), eventName actually (custom, kako sakame)
      owner: ekrajchevska
      repository: fastapi-auth
      webhook:
        endpoint: /auth-ms
        port: "12001"
        method: POST
        url: http://localhost
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json
